server:
  port: 8082
spring:
  application:
    name: seal-service
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health #检测实例健康
        health-check- interval: 10s
        #每隔1es检查
        hostname: localhost
        #配置实例地址
        register: true # 自动注册
        service-name: ${spring.application.name} #实例名称
      host: localhost
      port: 8500
  datasource:
    username: root
    password: gzou
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #driver-class-name: com.mysql.jdbc.Driver 这个驱动已经被弃用
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.imagehandle2022.entity
pkpath: D:\GZKF\code\pdf-services\src/main/resources/bhl.p12
srcPDFPath: D:\GZKF\pdf\
sealImagePath:
  0001: D:\GZKF\code\pdf-services\src\main\resources\pdf\chapter.png
  0002: D:\GZKF\code
signedPDFPath: D:\GZKF\pdf\
generatePath: D:\GZKF\pdf\
sealBasePath: D:\GZKF\seal\
rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDJfxfXOtxAdTHRpjrrUdfOcNg09DzLCodXOX23SAgKcz5Bc5ctsxq6pZ9gCUB8o0ULotI7KfoxqpQZ+KTd4V+j5w7V8SE3oWFDoAA2wzt8j0Zd1V09WkjQtm6BGeBRTcUxNHxW1zMazgAo85TQtSx+nfzzDlM14QtXp9/V6ibxYwIDAQAB
rsaPrivateKey: MIICWwIBAAKBgQDJfxfXOtxAdTHRpjrrUdfOcNg09DzLCodXOX23SAgKcz5Bc5ctsxq6pZ9gCUB8o0ULotI7KfoxqpQZ+KTd4V+j5w7V8SE3oWFDoAA2wzt8j0Zd1V09WkjQtm6BGeBRTcUxNHxW1zMazgAo85TQtSx+nfzzDlM14QtXp9/V6ibxYwIDAQABAoGANki/K4T4AYWRPmICTZNnCH7uQJXsKudTPvSGIfKN+ALEKu3xNKaj9NTZ8w2LCgkSeOgMq1PLy8Wg0L5j7ELjeNINyJP1cZ9ZydQNczNZqpZw4HyrqpzIAQpodBNjOtJWVBvijsz7NXUAtoWRPTlm0eUX8smKgzRKEvGap1DGLYECQQDyOFdvRMjY9NkXLUEAK++TpnzDG3x2rP14lYBBGiFT0mKK9nmMMU/ACJ3tsgHFYW8CEMwoP8ZbHKA/fFxDkxIJAkEA1PWololqa+0nLEVXavNHJxJ/Us47uIlp4jC3mTgeunuWX2v1bTI+WZ84WAN6dFD8pSzg7rLb/taZxpxqSiqTCwJAVVXWMARKwmzYwtqVqOrRt/ISyGY5nlHp5v68tbLwBOj9ALo/Lk39K8mdYi2xhAmEo3SpiJCXYGggaN12X/RDiQJANCM0tC5OdL/qAEe1wERxXhqEO5SsQGC8IJmGyadYtpU9Wn1G6AYOB8kYdUvctg+B2zqiky4M+FY37c0rpJ7JwwJAD8mzDLELiqKaIX9M78XK1Je27FF31GBv4c1UW0Ye2cg5VNIv2mSVH/bkC1gEcvmNhWe4wwB3wSS1cL5Z5GndZA==